### ISSUE TITLE
Error: Point2D not in triangle during triangulation

### ISSUE THREAD

**Issue by eugene-kirzhanov** [korlibs/korma#10]
Hi.
Trying to use triangulate functionality and on some set of points I receive

java.lang.Error: Point2d not in triangle
  at com.soywiz.korma.geom.triangle.TriangleKt.getPointIndexOffset(Triangle.kt:158)
  at com.soywiz.korma.geom.triangle.TriangleKt.pointCCW(Triangle.kt:163)
  at com.soywiz.korma.triangle.internal.Sweep.edgeEventByPoints(Poly2Tri.kt:260)
  at com.soywiz.korma.triangle.internal.Sweep.edgeEventByEdge(Poly2Tri.kt:254)
  at com.soywiz.korma.triangle.internal.Sweep.sweepPoints(Poly2Tri.kt:205)
  at com.soywiz.korma.triangle.internal.Sweep.triangulate(Poly2Tri.kt:195)
  at com.soywiz.korma.triangle.triangulate.TriangulateKt.triangulate(Triangulate.kt:12)

Example set:
-371.182, 307.381
-365.909, 310.721
-369.425, 318.455
-373.468, 317.048
-375.401, 315.818
-376.28, 314.588
-376.28, 313.357
-375.753, 311.599
-373.643, 307.733
-372.764, 307.029
-372.061, 307.029

![2020-02-27 031426](https://user-images.githubusercontent.com/44801988/75400119-5560a500-590f-11ea-8ec6-e9870fe1c50f.jpg)

I've tried to close polyline (by adding first point to the end of list) and reverse points order - error still happenes.

Tried to use one of another Poly2Tri java implementation and it works

**Comment by soywiz** [comment]
Have you tried to use those points as integers, multiplied them by 1000? Just to know if it is a rounding issue.
Which Java library have you used so I can try and compare results

**Comment by eugene-kirzhanov** [comment]
Thanks for the answer.
I'll check with integer values.
Previously I've used orbisgis/poly2tri.java implementation.

**Comment by eugene-kirzhanov** [comment]
I've tried with points multiplied by 1000 (double, not integer, because there is no triangluate() function on List<PointInt>) - same error occurs.

**Comment by eugene-kirzhanov** [comment]
Yet another set of points

```
import com.soywiz.korma.geom.Point
import com.soywiz.korma.triangle.triangulate.triangulate

private val points = listOf(
    Point(3, 10),
    Point(1, 5),
    Point(3, 1),
    Point(4, 0),
    Point(6, 0)
)

fun main() {
    points.triangulate()
}
```

![2020-02-28 212053](https://user-images.githubusercontent.com/44801988/75574929-3f1e2a80-5a70-11ea-9fd6-01eaa604a086.jpg)
