### ISSUE TITLE
Feature request: Apply transformation matrix to point(s)

### ISSUE THREAD

**Issue by baruchn** [korlibs/korma#12]
Forgive me if it already exists but I couldn't find it.

It would be very helpful for me, and I assume others, if I could apply a matrix to a point similar to 
[android.graphics.Matrix. mapPoints()](https://developer.android.com/reference/android/graphics/Matrix#mapPoints(float%5B%5D))

**Comment by soywiz** [comment]
You can use:
https://github.com/korlibs/korma/blob/4273bd8789c6379ef0c68fd69f040a1765a22823/korma/src/commonMain/kotlin/com/soywiz/korma/geom/Matrix.kt#L330

**Comment by soywiz** [comment]
You can add to your code something like this (untested):

```
 fun IMatrix.mapPoints(points: FloatArray) {
    for (n in 0 until points.size step 2) {
        val x = this.points[n + 0].toDouble()
        val y = this.points[n + 1].toDouble()
        this.points[n + 0] = transformX(x, y).toFloat()
        this.points[n + 1] = transformY(x, y).toFloat()
    }
}
```

**Comment by baruchn** [comment]
Will this apply also the scale, rotation and skew or just the translation?

**Comment by soywiz** [comment]
Applies the matrix to each point (that includes scale, rotation, skew and translations)

**Comment by baruchn** [comment]
Thanks. It seems to be working exactly as you described.
Small fix to the code in case someone else will need it:
```kotlin
fun IMatrix.mapPoints(points: FloatArray) {
    for (n in points.indices step 2) {
        val x = points[n + 0].toDouble()
        val y = points[n + 1].toDouble()
        points[n + 0] = transformX(x, y).toFloat()
        points[n + 1] = transformY(x, y).toFloat()
    }
}
```
