### ISSUE TITLE
Inclusive containsPoint

### ISSUE THREAD

**Issue by hooliooo** [korlibs/korma#13]
Hi there,

I'm currently using the library to evaluate the coordinates between shapes so let's say I have a 
VectorPath with the following coordinates:
(10, 10), (60, 10), (60, 0) (80, 0), (80, 90), and (10, 90)

And I have a Shape2d with the following coordinates:
(10, 80), (25, 80), (25, 90), and (10, 90)

I'd expect that VectorPath.containsPoint(25, 90) would return true because the point is on the line between (10,90) and (80,90). It seems containsPoint is exclusive for the upperBound. Is there another method to include it?

**Comment by soywiz** [comment]
Sorry for the delay. Did you closed it because you don't need anymore? I'm scheduling tasks to do right now

**Comment by hooliooo** [comment]
Yes. I closed it because I didn't need it anymore :)
