### ISSUE TITLE
Shape2d.collidesWith issue

### ISSUE THREAD

**Issue by hooliooo** [korlibs/korma#36]
Hello,

I'm using the `collidesWith` function on the Shape2d.Rectangle and I am getting unexpected results:

```
val rect1 = Shape2d.Rectangle(
  x = 15.503612232813342,
  y = 29.187611816208875,
  width = 9.525771277108397,
  height = 8.205535424065108
)

// rect1.right == 25.02938350992174

val rect2 = Shape2d.Rectangle(
  x = 25.648207133295152,
  y = 28.226381294575567,
  width = 14.579502618999763,
  height = 12.297989263608322
)
```

I expect `rect1.collideWith(rect2)` to return false but it returns true. They're next to each other but not colliding.

**Comment by emign** [comment]
`.collidesWith(view)` is an extension function of `View` not of `Shape2d`
https://github.com/korlibs/korge/blob/69b2dcc61f1c0cc004f3b1d28ca290274fdcd231/korge/src/commonMain/kotlin/com/soywiz/korge/view/ViewCollision.kt#L63

Try this:
```
val rect1 = SolidRect(100.0, 100.0, Colors.GREEN)
val rect2 = SolidRect(100.0, 100.0, Colors.GREEN).xy(200.0, 200.0)

rect1.collidesWith(rect2)
```

**Comment by hooliooo** [comment]
I only need the geometry functions and objects, there's no UI involved. I'm really just checking if 2D shapes intersect with each other.

**Comment by soywiz** [comment]
@hooliooo KorMA uses fixed-point arithmetic for this. In a future version we will probably only support integeral values for shapes as Android does to avoid this kind of problem. Right now double values are converted into fixed point integers. So right now it is like if you multiply the values by 20 and get the integer part.

You can by yourself adjust the precision by multiplying your values for example by 1000 to get 3 digit precision

**Comment by hooliooo** [comment]
Alright thanks for the advice
