### ISSUE TITLE
Get rid of underscores in IRectangle

### ISSUE THREAD

**Issue by SerVB** [korlibs/korma#45]
Current state seems to have redundant properties:

```kotlin
interface IRectangle {
    val _x: Double
    val _y: Double
    val _width: Double
    val _height: Double
}
val IRectangle.x get() = _x
val IRectangle.y get() = _y
val IRectangle.width get() = _width
val IRectangle.height get() = _height
```

I think it can become like this:
```kotlin
interface IRectangle {
    val x: Double
    val y: Double
    val width: Double
    val height: Double
}
```

As [discussed](https://discord.com/channels/728582275884908604/728616376910217258/794909014184951828), it can be handy but low-performant on native.

**Comment by soywiz** [comment]
After doing this, we should be able to implement korlibs/korge#606 .

It seems that Point at least is implementing IPoint without the underscores. Maybe we can just assume the performance hit on kotlin-native for now:
https://github.com/korlibs/korma/blob/fb7c2de33571795c69d606b59c1ed0e1f12ad83d/korma/src/commonMain/kotlin/com/soywiz/korma/geom/Point.kt#L9-L20
