### ISSUE TITLE
Interop with Swift / Objective C

### ISSUE THREAD

**Issue by schmidt9** [korlibs/korma#50]
Suppose I have a KMM project with Kotlin function in `common` containing `size: Size` param which becomes `Any` in Swift wrapper or `id` in ObjC. 

Now if I need to call this function and pass `size` var - how can I construct `Size` to pass it from Swift / ObjC to Kotlin? Do I need to write my own `expect` wrapper for `CGSize`?

**Comment by schmidt9** [comment]
I see some generated types here with my library prefix, but there is no Size in this list

![Снимок экрана 2021-04-12 в 16 25 18](https://user-images.githubusercontent.com/20910077/114401759-e514f180-9bab-11eb-845e-00bc588ca348.png)

**Comment by soywiz** [comment]
Unfortunately korlibs are not designed with interoperability in mind. That means that we are using inline classes wrapping other types in some cases which do not interop well right now and thats on the Kotlin roof. That might be the case and we cannot do something.
Once inline classes support multiple values we will use them. If the Kotlin team use structures on the Swift world, you will be able to use it directly in future versions. In the meantime you will have to figure out yourself interoperability or create intermediate methods and classes to ease interoperability

**Comment by schmidt9** [comment]
Sorry but I don't get why there is `MKMLKormaPoint` but no `MKMLKormaSize` in this list?

> I see some generated types here with my library prefix, but there is no Size in this list
> 
> ![Снимок экрана 2021-04-12 в 16 25 18](https://user-images.githubusercontent.com/20910077/114401759-e514f180-9bab-11eb-845e-00bc588ca348.png)

**Comment by soywiz** [comment]
https://github.com/korlibs/korma/blob/25d5c0fcb4905891d03b6b8a4185186c3d6cf364/korma/src/commonMain/kotlin/com/soywiz/korma/geom/Size.kt#L22

Size is an inline class wrapping Point, so you could convert between them without further allocations.

**Comment by schmidt9** [comment]
@soywiz thanks for explanation, I leave here related links, hope they'll figure this out
https://youtrack.jetbrains.com/issue/KT-32352
https://kotlinlang.org/docs/native-objc-interop.html#unsupported
