### ISSUE TITLE
bintray is no more

### ISSUE THREAD

**Issue by hamoid** [korlibs/korma#51]
Hi :)

Bintray has been sunset. I see  a commit preparing to use central instead. What's the current state of this transition?

The readme still shows Bintray is the way to go, which doesn't seem to work...

**Comment by soywiz** [comment]
The status: all the korlibs are on central already. There are a couple of versions published: https://search.maven.org/artifact/com.soywiz.korlibs.korma/korma

Just created this issue to tackle the README issue: https://github.com/korlibs/korge-next/issues/253

Hope it helps :)
