### ISSUE TITLE
Creates errors when android Project has unsigned variables

### ISSUE THREAD

**Issue by adamshick-Skyward** [korlibs/korma#54]
I upgraded from 2.0.9 to the latest and get the following errors on my unsigned variables: Please make sure you have the required dependencies for unsigned types in the classpath. When I lower back down to 2.0.9 it works just fine.

**Comment by soywiz** [comment]
Is latest 2.2.1? In which target the issue arises? Which Kotlin version? Is it a IDE issue, or issue when compiling? Can you provide a screenshot?

**Comment by adamshick-Skyward** [comment]
This is the error I see
![Screen Shot 2021-07-08 at 9 43 20 AM](https://user-images.githubusercontent.com/71104450/124960565-4ee93f80-dfd1-11eb-97a7-77930a58d633.png)
For this line of code `rthMinAltitude(20u)`

Kotlin version is: 1.4.31

**Comment by soywiz** [comment]
Please, try with Kotlin 1.5.20. I believe that was a bug in Kotlin that was fixed already in 1.5.20

**Comment by adamshick-Skyward** [comment]
Yup that fixed it. Thanks!!
